[features]
seeds = false
skip-lint = false
[programs.devnet]
solana_rng = "5ATEphZm1fSphpzBm1rbmKsGyEy9VhXtFJ4n3scV5gwc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/raidr/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
