[features]
seeds = false
skip-lint = false
[programs.devnet]
solana_rng = "BwLNj3u23Nuh8aipqpa8axPE1R45atztb5HkxesU2qLx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/raidr/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
